version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
      args:
        NODE_VERSION: ${NODE_VERSION:-20.13.1}
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      NODE_ENV: development
      MONGODB_URI: ${MONGODB_URI}
    ports:
      - '3000:3000'
    container_name: nestjs-todo-api-dev
