version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NODE_VERSION: ${NODE_VERSION:-20.13.1}
    environment:
      - MONGODB_URI=${MONGODB_URI}
      - NODE_ENV=production
    ports:
      - '3000:3000'
    container_name: nestjs-todo-api
